worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    upstream web_backend { server web:5000; }
    server {
        listen 80 default_server;
        server_name _;
        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /nginx-health {
            access_log off;
            return 200 "healthy\n";
        }
    }
}
